### ISSUE TITLE
Use normalize css instead of a self built version

### ISSUE THREAD

**Issue by lil5** [tretapey/raisincss#11]
https://necolas.github.io/normalize.css/

To implement a major version bump may be required as some websites may break

**Comment by tretapey** [comment]
@lil5 once installed.. should we remove _setup.scss?

**Comment by lil5** [comment]
I feel we should advice devs to add it them selves either by adding the CDN or at `yarn add `

**Comment by lil5** [comment]
It seems I'm a little behind the times on this one, NormalizeCSS has not changed and most css frameworks use their own version.

Personally I'm infavor of renaming the file `_setup.scss` to something more like `normalize` or `base`.

**Comment by tretapey** [comment]
@lil5 I agree that _setup.scss should be renamed to _base.scss, let  keep this on hold for the moment
