### ISSUE TITLE
Use a mixin for adding breakpoint classes

### ISSUE THREAD

**Issue by lil5** [tretapey/raisincss#12]
It seem that there is a lot of duplicate code to add breakpoint classes.

**Comment by lil5** [comment]
https://github.com/lil5/raisincss/tree/%2312-use-mixin-for-breakpoint-classes?files=1

**Comment by tretapey** [comment]
@jenaro94 Let me know your ideas about this

**Comment by tretapey** [comment]
@lil5 I was reviewing your mixin, it looks really good, did you tested it? what about adding that in PR so I can test it?

**Comment by lil5** [comment]
Cheers but I’m not yet happy about the mixin name. I haven’t finished the refactor to use the mixin with all file yet.give me time and I’ll have a PR for you 😉

**Comment by tretapey** [comment]
@lil5 of course, all the time of the world. Let me know if I can help.
