### ISSUE TITLE
use !default behind all variables

### ISSUE THREAD

**Issue by lil5** [tretapey/raisincss#15]
This allows devs to override the initialization of variables with their own values 

https://thoughtbot.com/blog/sass-default

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by tretapey** [comment]
@lil5  I merged this to master, good contrib BTW. Can you please add this and the prefix thing (merged as well) to the docs please?

**Comment by lil5** [comment]
Definitely!

Although I'm creating a branch for the new docs site :wink: 
Shall I just add it there instead?

**Comment by tretapey** [comment]
Awesome!!

**Comment by lil5** [comment]
https://github.com/tretapey/raisincss/pull/18/commits/d71f5f3dd0cdd750b2486f88c0076dbfa76d8a55

This is the specific commit that adds documentation of the prefix variable from PR #18

**Comment by tretapey** [comment]
Merged!
