### ISSUE TITLE
Create a variable to add a prefix to all classes

### ISSUE THREAD

**Issue by lil5** [tretapey/raisincss#7]
e.g. 
If `$prefix` is not added default to `.flex`,
Otherwise if `$prefix: "rs-";` flex class will look like this: `.rs-flex`.

**Comment by lil5** [comment]
see #8

**Comment by tretapey** [comment]
I like this.. will review asap

**Comment by tretapey** [comment]
@lil5 I merged this with develop, looks good, do you think we should add a flag in the build task to add that prefix from build command, is that possible?

**Comment by lil5** [comment]
I’m afraid not,

In the documentation it seemed possible with `stdin` flag and merging that with the other scss file but this line from the documentation states that it will not work, personally it seemed to much of a hack too.

> The --stdin flag may not be used with many-to-many mode.
https://sass-lang.com/documentation/cli/dart-sass#options

**Comment by lil5** [comment]
The best option for outside use of variable edits are use of `!default`.

https://thoughtbot.com/blog/sass-default
Here might be the best explanation.

**Comment by tretapey** [comment]
@lil5  thank you! I will check that.

**Comment by tretapey** [comment]
Closing this.. will be completed whit #16
